config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :stories do
    member do
      post :like
    end
  end

  delete '/logout', to: 'session#destroy', as: :logout
  get '/auth/:provider/callback', to: 'sessions#create'

  root to: 'stories#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  # validates_format_of :title, :with => /\A^\d+,?\Z/
  validates :title, :format => {:with => /\A^\d+,?\Z/, :message => 'format'}
end

app/models/story.rb
class Story < ActiveRecord::Base
  include PublicActivity::Model


  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true


  tracked owner: Proc.new { |controller, model| controller.current_user ? controller.current_user : nil }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :stories

  class << self
    def from_omniauth(auth)
      user = User.find_or_initialize_by(uid: auth['uid'])
      user.name = auth['info']['name']
      user.avatar_url = auth['info']['image']
      user.save!
      user
    end
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include PublicActivity::StoreController


  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  hide_action :current_user


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(request.env['omniauth.auth'])
    session[:user_id] = user.id
    flash[:success] = "Welcome, #{user.name}"
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Goodbye!"
    redirect_to root_url
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :find_story, only: [:destroy, :show, :edit, :update, :like]
  before_action :load_activities, only: [:index, :show, :new, :edit]


  def index
    @stories = Story.order('created_at DESC')
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    if @story.save
      # flash[:success] = 'Your story was added!'
      redirect_to root_path, notice: t('.notice')
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @story.update_attributes(story_params)
      # flash[:success] = 'The story was edited!'
      redirect_to root_path, notice: t('.notice')
    else
      render 'edit'
    end
  end

  def destroy
    if @story.destroy
      # flash[:success] = 'The story was deleted!'
    else
      # flash[:error] = 'Cannot delete this story...'
    end
    redirect_to root_path, notice: t('.notice')
  end

  def show
  end

  def like
    without_tracking do
      @story.increment!(:likes)
    end
    @story.create_activity :like
    # flash[:success] = 'Thanks for sharing your opinion!'
    redirect_to story_path(@story), notice: t('.notice')
  end

  private

  def without_tracking
    Story.public_activity_off
    yield if block_given?
    Story.public_activity_on
  end

  def story_params
    params.require(:story).permit(:title, :body)
  end

  def find_story
    @story = Story.find(params[:id])
  end

  def load_activities
    @activities = PublicActivity::Activity.order('created_at DESC').limit(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_header(header)
    content_for(:page_header) { header.to_s }
  end

  def get_guest_name
    return ["王学兵", "邱启明", "angelababy", "唐嫣", "聂远", "孙宁", "吴京", "张子萱", "钟汉良", "陈赫", "李健", "李易峰", "黄晓明", "邓紫棋", "陈乔恩", "范冰冰", "郑爽", "杨幂", "鹿晗", "郭德纲", "张智霖", "萧煌奇", "邓超", "李晨", "井柏然", "刘诗诗", "吴亦凡", "赵本山", "权志龙", "张靓颖", "池昌旭", "金钟国", "成龙", "张馨予", "何炅", "郑恺", "宋智孝", "刘德华", "周杰伦", "李玉刚", "朴信惠", "姚贝娜", "少女时代", "李钟硕", "周星驰", "刘恺威", "金秀贤", "王宝强", "谭维维", "佟丽娅", "柴静", "王思聪", "王菁", "芮成钢", "黄灿灿", "最帅快递小哥", "王学兵老婆", "郭美美", "最牛实习妹", "祁可欣", "白丽清", "徐才厚", "张芊芊", "李菡", "王自如", "傅莹", "赵本水", "莲花小王子", "周永康", "度娘", "李小璐", "董思阳", "朱丽倩", "无鼻女", "罗永浩", "董海涛", "魏坤琳", "陆毅", "刘强东", "孙维", "李宗瑞", "徐小明", "薄熙来", "带头大哥777", "邓建国", "凤姐", "柯震东", "李刚", "张碧晨", "黄海波", "舟舟", "黄磊", "iphone女", "陈静仪", "南大最萌小师妹", "韩苗可", "小彩旗", "grace", "吴镇宇", "刘亦菲", "赵韩樱子", "孙俪", "赵丽颖", "宋茜", "谢娜", "高圆圆", "陈妍希", "柳岩", "张敏", "赵奕欢", "古力娜扎", "赵薇", "叶一茜", "徐露", "倪妮", "舒畅", "李依晓", "吴昕", "张钧甯", "谢楠", "张柏芝", "高露", "尹恩惠", "袁咏仪", "杨紫", "景甜", "全智贤", "郑秀晶", "刘涛", "林心如", "李宇春", "林鹏", "周迅", "徐静蕾", "林允儿", "马云", "李彦宏", "马化腾", "雷军", "乔布斯", "史玉柱", "比尔盖茨", "李开复", "周鸿祎", "张朝阳", "柳传志", "任正非", "唐骏", "贾跃亭", "姚劲波", "茅侃侃", "丁磊", "杨元庆", "陈天桥", "蔡文胜", "薛蛮子", "扎克伯格", "陆兆禧", "孙亚芳", "徐新", "李一男", "张亚勤", "杨致远", "李明远", "王小川", "张志东", "傅盛", "彭蕾", "陈一丹", "李学凌", "高燃", "朱骏", "方滨兴", "曹国伟", "李国庆", "古永锵", "沈南鹏", "余楚媛", "王志东", "求伯君", "王江民", "陈华", "施密特"].sample
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('title')%></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to t('title'), root_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav pull-right">
      <% if current_user %>
          <li><span><%= image_tag current_user.avatar_url, alt: current_user.name %></span></li>
          <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
      <% else %>
          <li><%= link_to t('login_fb'), '/auth/facebook' %></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="container">
  <div class="page-header">
    <h1><%= yield :page_header %></h1>
  </div>

  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
  <% end %>

  <!--<%= yield %>-->

  <div class="col-sm-9">
    <%= yield %>
  </div>

  <%= render 'shared/activities' %>


</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>编辑段子</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>段子集</h1>

<table>
  <thead>
    <tr>
      <th>名称</th>
      <th>内容</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to '详细', post %></td>
        <td><%= link_to '编辑', edit_post_path(post) %></td>
        <td><%= link_to '删除', post, method: :delete, data: { confirm: '确定?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新段子?', new_post_path %>

app/views/posts/new.html.erb
<h1>新段子</h1>

<%= render 'form' %>

<%= link_to '回去', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>名称:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>内容:</strong>
  <%= @post.body %>
</p>

<%= link_to '编辑', edit_post_path(@post) %> |
<%= link_to '回去', posts_path %>

app/views/public_activity/story/_create.html.erb
<li class="list-group-item">
  <span class="glyphicon glyphicon-plus"></span>
  <small class="text-muted"><%= a.created_at.strftime('%H:%M:%S %-d %B %Y') %></small>
  <br/>
  <strong><%= activity.owner ? activity.owner.name : get_guest_name %></strong>
  <% if a.trackable %>
      <%= t('activity.story.create') %> <%= link_to a.trackable.title, story_path(a.trackable) %>.
  <% else %>
      <%= t('activity.story.destroy') %>
  <% end %>
</li>

app/views/public_activity/story/_destroy.html.erb
<li class="list-group-item">
  <span class="glyphicon glyphicon-remove"></span>
  <small class="text-muted"><%= a.created_at.strftime('%H:%M:%S %-d %B %Y') %></small><br/>
  <strong><%= activity.owner ? activity.owner.name : get_guest_name %></strong>
  <%= t('activity.story.destroy')%>
</li>

app/views/public_activity/story/_update.html.erb
<li class="list-group-item">
  <span class="glyphicon glyphicon-edit"></span>
  <small class="text-muted"><%= a.created_at.strftime('%H:%M:%S %-d %B %Y') %></small><br/>
  <strong><%= activity.owner ? activity.owner.name : get_guest_name %></strong>
  <% if a.trackable %>
      <%= t('activity.story.update')%> <%= link_to a.trackable.title, story_path(a.trackable) %>.
  <% else %>
      <%= t('activity.story.destroy')%>
  <% end %>
</li>

app/views/shared/_activities.html.erb
<div class="col-sm-3">
  <ul class="list-group">
    <% @activities.each do |activity| %>
        <li class="list-group-item">
          <span class="glyphicon glyphicon-<%= activity.key.match(/\.(.*)/)[1] %>"></span>
          <strong><%= activity.owner ? activity.owner.name : get_guest_name %></strong>
          <%= render_activity activity, display: :i18n %>
          <% if activity.trackable %>
              "<%= link_to activity.trackable.title, story_path(activity.trackable) %>"
          <% else %>
               <%== t('activity.destroy')%>
          <% end %>
        </li>
    <% end %>
  </ul>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title">The following errors were found while submitting the form:</h3>
      </div>

      <div class="panel-body">
        <ul>
          <% object.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
<% end %>

app/views/stories/_form.html.erb
<%= form_for @story do |f| %>
    <%= render 'shared/errors', object: @story %>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', required: true %>
    </div>

    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control', required: true, cols: 3 %>
    </div>

    <%= f.submit class: 'btn btn-primary' %>

<% end %>

app/views/stories/edit.html.erb
<% page_header t('story.create') %>

<%= render 'form' %>

app/views/stories/index.html.erb
<% page_header t('slogan') %>

<p><%= link_to t('story.create'), new_story_path, class: 'btn btn-primary btn-large' %></p>

<% @stories.each do |story| %>
    <div class="well well-lg">
      <h2><%= link_to story.title, story_path(story) %></h2>

      <p><%= truncate(story.body, length: 350) %></p>

      <div class="btn-group">
        <%= link_to t('story.edit'), edit_story_path(story), class: 'btn btn-info' %>
        <%= link_to t('story.destroy'), story_path(story), data: {confirm: t('story.sure')}, method: :delete, class: 'btn btn-danger' %>
      </div>
    </div>
<% end %>

app/views/stories/new.html.erb
<% page_header t('story.create') %>

<%= render 'form' %>

app/views/stories/show.html.erb
<% page_header @story.title %>

<p>
  <span class="label label-default"><%= @story.likes || 0 %> <%=t('story.likes') %></span>
  <%= link_to content_tag(:span, '', class: 'glyphicon glyphicon-thumbs-up') +  t('like'),
              like_story_path(@story), class: 'btn btn-default btn-sm', method: :post %>
</p>

<p><%= @story.body %></p>

<div class="btn-group">
  <%= link_to t('story.edit'), edit_story_path(@story), class: 'btn btn-info' %>
  <%= link_to t('story.destroy'), story_path(@story), data: {confirm: t('story.sure')}, method: :delete, class: 'btn btn-danger' %>
</div>